name: code_health
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/DisDis/code_health
author: Igor Demyanov <igor.demyanov@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build_runner: ^0.10.2
  build_runner_core: ^0.3.1+5
  build: ^0.12.7+3
  analyzer: ^0.32.5
  package_resolver: ^1.0.6

dev_dependencies:
  test: ^1.0.0

#PUB_HOSTED_URL=https://pub.dartlang.org/ pub upgrade
