name: code_health
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/DisDis/code_health
author: Igor Demyanov <igor.demyanov@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  build_runner: ^1.3.4
  build_runner_core: ^3.1.1
  build: 1.1.6
  analyzer: ^0.36.3
  dart_style: ^1.2.5
  yaml: ^2.2.0

dev_dependencies:
  test: ^1.0.0

#PUB_HOSTED_URL=https://pub.dartlang.org/ pub upgrade
