name: code_health
description: A sample command-line application.
version: 1.1.0
homepage: https://github.com/DisDis/code_health
author: Igor Demyanov <igor.demyanov@gmail.com>

environment:
  sdk: '>=2.6.1 <3.0.0'

dependencies:
  build_runner: 1.8.0
  build_runner_core: 4.5.2
  build: 1.2.2
  analyzer: 0.39.4
  dart_style: 1.3.3
  yaml: 2.2.0
  path: 1.6.4

dev_dependencies:
  test: ^1.0.0

#PUB_HOSTED_URL=https://pub.dartlang.org/ pub upgrade
