name: code_health
description: A sample command-line application.
 version: 1.0.0
# homepage: https://www.example.com
# author: dis <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  build_runner: ^0.10.0
  analyzer: ^0.32.5

dev_dependencies:
  test: ^1.0.0
